# Generated by Django 4.2 on 2023-06-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_link_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
